#!/usr/bin/bash
set -euo pipefail

: "${GIT_ROOT:="$(git rev-parse --show-toplevel)"}"
: "${GIT_AGAINST:=HEAD}"

if ! git rev-parse --verify HEAD >/dev/null 2>&1; then
  # Initial commit: diff against an empty tree object
  GIT_AGAINST="$(git hash-object -t tree /dev/null)"
fi

whitespaces() {
  # If there are whitespace errors, print the offending file names
  git diff-index --check "$GIT_AGAINST" -- ||
    echo "You have some trailing whitespaces 🙈"
}
