version: '3'

services:
  db_project_api:
    image: public.ecr.aws/docker/library/postgres:16
    container_name: db_project_api
    environment:
      - POSTGRES_DB=dev_project_api
      - POSTGRES_USER=dev_db
      - POSTGRES_PASSWORD=dev_db
    ports:
      - '5433:5432'
