version: '3.3'

services:
  db_financial_aid:
    image: public.ecr.aws/docker/library/postgres:15.3-alpine
    container_name: db_financial_aid
    networks:
      - local
    environment:
      - POSTGRES_DB=dev_db
      - POSTGRES_USER=dev_db
      - POSTGRES_PASSWORD=dev_db
    ports:
      - 5433:5432

networks:
  local:
