comment:
  layout: 'reach, diff, flags, files, header, footer, feedback'
  behavior: default
github_checks: false
coverage:
  status:
    project: false
    patch: false
flag_management:
  default_rules:
    carryforward: true
component_management:
  default_rules: # default rules that will be inherited by all components
    statuses:
      - type: project # in this case every component that doens't have a status defined will have a project type one
        target: auto
        informational: true
        branches:
          - '!main'
  individual_components:
    - component_id: api-graphql
      name: Portal GraphQL (Not Prioritised)
      paths:
        - apps/api/**
        - libs/api/domains/**
    - component_id: microservices
      name: All REST APIs except Application System API.
      paths:
        - apps/services/**
        - apps/air-discount-scheme/backend/**
        - apps/download-service/**
        - libs/auth-api-lib/**
        - libs/services/**
    - component_id: auth-services
      name: Authentication related REST APIs
      paths:
        - apps/services/auth/**
        - libs/auth-api-lib/**
        - libs/services/auth/**
    - component_id: application-system-api
      name: Application System API
      paths:
        - apps/application-system/api/**
        - libs/application/api/**
        - libs/application/core/**
        - libs/application/graphql/**
        - libs/application/template-api-modules/**
        - libs/application/template-loader/**
        - libs/application/templates/**
    - component_id: react-libs
      name: React shared libraries
      paths:
        - libs/react/**
        - libs/react-spa/**
        - libs/shared/**
        - libs/auth/react/**
        - libs/next-ids-auth/**
    - component_id: nest-libs
      name: NestJS shared libraries
      paths:
        - libs/nest/**
        - libs/clients/middleware/**
        - libs/auth-nest-tools/**
    - component_id: island-ui
      name: Island UI
      paths:
        - libs/island-ui/**
